### PR TITLE
Add /health as watchdog url

### PR DESCRIPTION
**Pull request by mdegat01**
# Proposed Changes

> (Describe the changes and rationale behind them)

Grafana has a [/health API](https://grafana.com/docs/grafana/latest/http_api/other/#returns-health-information-about-grafana) which does not require authentication and basically just returns whether Grafana is happily running or not. Setting the watchdog URL to this makes it so watchdog calls it regularly and restarts the addon if it receives an unhealthy response. 

Since the internal port that grafana listens on [needs to stay open](https://github.com/hassio-addons/addon-grafana/pull/127#issuecomment-811690742) I figured we might as well use it for these health checks since watchdog will always be able to reach grafana here, regardless of other configuration.

I pulled this branch locally to test and it seems to be running without issue. I guess the one very small note to make is that if someone has set the environmental variable `GF_SERVER_HTTP_ADDR` in their config then watchdog won't like it since it will be denied access on port `3000`. That's actually how I confirmed it was working, I let addon run fine for about an hour then added this to the config and saw I got a warning from watchdog in my log:

```yaml
env_vars:
  - name: GF_SERVER_HTTP_ADDR
    value: 127.0.0.1
```

## Related Issues

> ([Github link][autolink-references] to related issues or pull requests)

[autolink-references]: https://help.github.com/articles/autolinked-references-and-urls/

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
The health state is not just Grafana in this case, it should go through the proxy.

**Comment by mdegat01** [comment]
So the problem with that is I don't have an easy way to figure out that port. When the user sets a value for the port then NGinx listens on `80`. But when the user does not and is running in Ingress mode then NGinx listens on 1337. Neither of those values is in config so I can't use the normal placeholders of `PORT` or a config value to get to the right spot.

To do that I think the easiest way would be to add a new server config that listens on a different unrelated port (`81`? `8080`?). That config pass through requests which exactly matched `/api/health` and reject everything else. Then I could use that URL for all configurations (Ingress and non-Ingress).

Let me know what you think about this approach.

**Comment by sinclairpaul** [comment]
The Ingress NGINX config is always enabled, if you assign a port it will configure both.

**Comment by frenck** [comment]
A user cannot disable Ingress.

**Comment by mdegat01** [comment]
Oh right, duh, its got `.conf` not `.disabled`. Ok cool, will use that, thanks!

**Comment by mdegat01** [comment]
Watchdog requests originate from supervisor not observer though right? Since observer runs at a different IP and so will be denied access at port 1337

**Comment by mdegat01** [comment]
Looks like its good. Updated it to use port `1337` and ran it locally for about a half an hour with watchdog on, didn't see any warnings.

**Review by frenck — APPROVED** [review]
Thanks, @mdegat01 👍

**Review by frenck — APPROVED** [review]

**Pull request merged**
